import Link from 'next/link';
import { clinicInfo, imageInventory } from '@/data/clinicInfo';
import { navItems } from '@/data/navigation';
import { services } from '@/data/services';
import { team } from '@/data/team';

export function Photo({label, className=''}:{label:string; className?:string}){return <div className={`relative overflow-hidden rounded-[28px] bg-[linear-gradient(135deg,#ead8cc,#fff8f2)] ${className}`}><div className="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_70%_30%,white,transparent_35%)]"/><div className="relative flex h-full min-h-[220px] items-center justify-center p-8 text-center text-sm font-bold text-[#7b655b]">TODO: add real {label} photo<br/><span className="mt-2 block max-w-sm text-xs font-medium">{imageInventory.note}</span></div></div>}
export function Header(){return <header className="sticky top-0 z-50 border-b border-[#eee4dd]/80 bg-[#fbfaf7]/90 backdrop-blur"><div className="container flex h-20 items-center justify-between"><Link href="/" className="font-black tracking-tight">fresh vibes</Link><nav className="hidden gap-8 text-sm md:flex">{navItems.map(i=><Link key={i.href} href={i.href} className="hover:text-[#9a7d4d]">{i.label}</Link>)}</nav><Link href="/contact" className="btn btn-dark">Objednat se</Link></div></header>}
export function Footer(){return <footer className="bg-[#140708] py-16 text-white"><div className="container grid gap-10 md:grid-cols-4"><div><h2 className="text-xl font-black uppercase">Fresh Vibes</h2><p className="mt-5 text-sm leading-7 text-white/65">{clinicInfo.description}</p></div><div><b>Explore</b>{navItems.map(i=><Link className="mt-3 block text-sm text-white/65" key={i.href} href={i.href}>{i.label}</Link>)}</div><div><b>Služby</b>{services.slice(0,5).map(s=><Link className="mt-3 block text-sm text-white/65" key={s.slug} href={`/services/${s.slug}`}>{s.title}</Link>)}</div><div><b>Kontakt</b><p className="mt-3 text-sm text-white/65">{clinicInfo.address}<br/>{clinicInfo.phone}<br/>{clinicInfo.email}<br/>{clinicInfo.openingHours.join(', ')}</p><div className="mt-6 flex gap-4 text-xs">{clinicInfo.social.map(s=><a key={s.label} href={s.href}>{s.label}</a>)}</div></div></div><div className="container mt-12 border-t border-white/10 pt-8 text-xs text-white/45">© 2026 Fresh Vibes · <Link href="/privacy">Privacy Policy</Link> · <Link href="/cookies">Cookies</Link> · <Link href="/legal">Legal notice</Link></div></footer>}
export function ContactForm(){return <form className="card grid gap-4 p-6" action="/api/contact" method="post"><input className="field" name="name" placeholder="Jméno" required/><input className="field" name="phone" placeholder="Telefon" required/><input className="field" name="email" type="email" placeholder="E-mail"/><select className="field" name="service">{services.map(s=><option key={s.slug}>{s.title}</option>)}</select><textarea className="field min-h-32" name="message" placeholder="Zpráva"/><label className="flex gap-3 text-sm text-[#756b66]"><input type="checkbox" required/> Souhlasím se zpracováním údajů pro odpověď na poptávku. Ošetření navrhne lékař po konzultaci.</label><button className="btn btn-dark" type="submit">Odeslat poptávku</button></form>}
export function ServicesList(){return <div className="grid gap-4">{services.map((s,i)=><Link key={s.slug} href={`/services/${s.slug}`} className="group grid gap-3 border-b border-[#e7ddd7] py-5 md:grid-cols-[80px_1fr_180px]"><span className="text-[#b9985f]">0{i+1}</span><span><b className="serif text-2xl font-normal group-hover:text-[#9a7d4d]">{s.title}</b><p className="mt-2 text-[#756b66]">{s.short}</p></span><span className="text-sm font-bold">{s.price}</span></Link>)}</div>}
export function TeamGrid(){return <div className="grid gap-5 md:grid-cols-3">{team.map(m=><article className="card overflow-hidden" key={m.name}><Photo label="doctor/team" className="h-72 rounded-none"/><div className="p-5"><h3 className="font-bold">{m.name}</h3><p className="text-sm text-[#9a7d4d]">{m.role}</p><p className="mt-3 text-sm text-[#756b66]">{m.bio}</p></div></article>)}</div>}
