'use client';
import { useState } from 'react';
import { Maximize2, Minus, Plus } from 'lucide-react';
import { SmileVisual } from './SmileVisual';

export function BeforeAfterSlider() {
  const [value, setValue] = useState(52);
  return <div className="premium-card p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.24em] text-gold">Before / after</p><h2 className="font-serif text-3xl font-semibold">Planned DSD preview</h2></div><div className="flex flex-wrap gap-2">{['Original','DSD Overlay','Proposed Result','3D Preview'].map((b)=><button key={b} className="ghost-button">{b}</button>)}</div></div><div className="relative h-[560px] overflow-hidden rounded-[34px] bg-charcoal shadow-premium"><SmileVisual className="absolute inset-0 h-full w-full"/><div className="absolute inset-0 overflow-hidden" style={{clipPath:`inset(0 0 0 ${value}%)`}}><SmileVisual overlay className="h-full w-full saturate-125 contrast-105"/></div><div className="absolute inset-y-0 z-20 w-1 bg-white shadow-[0_0_30px_rgba(255,255,255,.9)]" style={{left:`${value}%`}}><span className="absolute left-1/2 top-1/2 grid h-14 w-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-champagne bg-white text-gold shadow-premium">↔</span></div><span className="absolute left-5 top-5 rounded-full bg-charcoal/60 px-4 py-2 text-sm font-bold text-white">Before</span><span className="absolute right-5 top-5 rounded-full bg-champagne/90 px-4 py-2 text-sm font-bold text-charcoal">After</span><input aria-label="Comparison slider" type="range" min="8" max="92" value={value} onChange={(e)=>setValue(Number(e.target.value))} className="absolute inset-x-8 bottom-8 z-30 accent-champagne" /></div><div className="mt-4 flex justify-end gap-2"><button className="ghost-button"><Minus size={15}/></button><button className="ghost-button"><Plus size={15}/></button><button className="ghost-button"><Maximize2 size={15}/> Fullscreen</button></div></div>;
}
