import Link from 'next/link';
import { AppShell } from '@/components/layout/AppShell';
import { DSDAnalysisPanel } from '@/components/dsd/AnalysisPanel';
import { PatientAvatar } from '@/components/dsd/Avatar';
import { PhotoProtocolGrid } from '@/components/dsd/PhotoProtocolGrid';
import { ThreeDPreview } from '@/components/dsd/ThreeDPreview';
import { TreatmentPlanBuilder } from '@/components/dsd/TreatmentPlanBuilder';
import { getCase, getDoctor, getPatient } from '@/data/mock-dsd';
import { statusClass } from '@/lib/utils';

export default async function CasePage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const c=getCase(id), p=getPatient(c.patientId), d=getDoctor(c.doctorId); return <AppShell title={p.name} subtitle={`${c.treatmentType} · ${c.currentPhase}`}><div className="space-y-6"><div className="premium-card p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-5"><PatientAvatar name={p.name} tone={p.avatarTone} className="h-20 w-20"/><div><h2 className="font-serif text-4xl font-semibold">Patient DSD profile</h2><p className="mt-1 text-taupe">{p.age} · {p.gender} · {p.contact} · Assigned to {d.name}</p><p className="mt-2 text-sm text-taupe">Goal: {p.goals}</p></div></div><span className={`status-pill ${statusClass(c.status)}`}>{c.status}</span></div><div className="mt-6 flex flex-wrap gap-2">{['Overview','Photos','Analysis','Treatment','Documents','Notes'].map(t=><button key={t} className="ghost-button">{t}</button>)}<Link href={`/workspace/${c.id}`} className="gold-button">Open workspace</Link></div></div><div className="grid gap-6 xl:grid-cols-[1fr_390px]"><main className="space-y-6"><section className="premium-card p-6"><h2 className="section-title">Case overview</h2><p className="mt-3 text-taupe">{c.summary}</p><p className="mt-3 rounded-2xl bg-ivory p-4 text-sm text-taupe"><b className="text-charcoal">Clinical note:</b> {c.clinicalNotes}</p><div className="mt-5 grid gap-4 md:grid-cols-4">{[['Progress',`${c.progress}%`],['Revenue',c.revenue],['Priority',c.priority],['Exports',`${c.exports.length}`]].map(([a,b])=><div key={a} className="rounded-2xl bg-white p-4"><p className="text-sm text-taupe">{a}</p><b className="font-serif text-2xl">{b}</b></div>)}</div></section><PhotoProtocolGrid photos={c.photos}/><TreatmentPlanBuilder steps={c.treatmentPlan}/><ThreeDPreview/></main><aside className="space-y-6"><section className="premium-card p-5"><h2 className="section-title">Timeline</h2><div className="mt-5 space-y-4">{c.timeline.map(e=><div key={e.id} className="border-l-2 border-champagne/40 pl-4"><p className="font-semibold">{e.label}</p><p className="text-xs text-gold">{e.date}</p><p className="text-sm text-taupe">{e.detail}</p></div>)}</div></section><section className="premium-card p-5"><h2 className="section-title">Export status</h2><div className="mt-4 space-y-3">{c.exports.map(e=><div key={e.id} className="rounded-2xl bg-white p-3"><div className="flex justify-between"><b>{e.type}</b><span className={`status-pill ${statusClass(e.status)}`}>{e.status}</span></div><p className="text-sm text-taupe">Updated {e.updatedAt}</p></div>)}</div></section></aside></div><DSDAnalysisPanel metrics={c.metrics.slice(0,4)}/></div></AppShell> }
